# browser seçenekleri: chrome, firefox, edge
browser=chrome

# Test Ortam? URL'i
url=https://www.saucedemo.com/

# Geçerli Kullan?c? Bilgileri
username=standard_user
password=secret_sauce
wrongPassword=1

# Bekleme Süresi (Saniye)
timeout=15